package ar.com.templateit.cds.web.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Sun Jan 24 22:39:35 ARST 2016
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://service.web.cds.templateit.com.ar/", name = "CategoriaService")
@XmlSeeAlso({ObjectFactory.class})
public interface CategoriaService {

    @WebResult(name = "getCategoria", targetNamespace = "")
    @RequestWrapper(localName = "getCategoria", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.GetCategoria")
    @ResponseWrapper(localName = "getCategoriaResponse", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.GetCategoriaResponse")
    @WebMethod
    public ar.com.templateit.cds.web.service.Categoria getCategoria(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebResult(name = "loadAllCategoria", targetNamespace = "")
    @RequestWrapper(localName = "loadAllCategoria", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.LoadAllCategoria")
    @ResponseWrapper(localName = "loadAllCategoriaResponse", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.LoadAllCategoriaResponse")
    @WebMethod
    public java.util.List<ar.com.templateit.cds.web.service.Categoria> loadAllCategoria();

    @WebResult(name = "findByCriteria", targetNamespace = "")
    @RequestWrapper(localName = "findByCriteria", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.FindByCriteria")
    @ResponseWrapper(localName = "findByCriteriaResponse", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.FindByCriteriaResponse")
    @WebMethod
    public java.util.List<ar.com.templateit.cds.web.service.Categoria> findByCriteria(
        @WebParam(name = "nombre", targetNamespace = "")
        java.lang.String nombre
    );
}
