package ar.com.templateit.cds.web.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Sun Jan 24 22:40:39 ARST 2016
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://service.web.cds.templateit.com.ar/", name = "ProductoService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductoService {

    @WebResult(name = "loadAllProducto", targetNamespace = "")
    @RequestWrapper(localName = "loadAllProducto", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.LoadAllProducto")
    @ResponseWrapper(localName = "loadAllProductoResponse", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.LoadAllProductoResponse")
    @WebMethod
    public java.util.List<ar.com.templateit.cds.web.service.Producto> loadAllProducto();

    @WebResult(name = "getProducto", targetNamespace = "")
    @RequestWrapper(localName = "getProducto", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.GetProducto")
    @ResponseWrapper(localName = "getProductoResponse", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.GetProductoResponse")
    @WebMethod
    public ar.com.templateit.cds.web.service.Producto getProducto(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebResult(name = "findByCriteria", targetNamespace = "")
    @RequestWrapper(localName = "findByCriteria", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.FindByCriteria")
    @ResponseWrapper(localName = "findByCriteriaResponse", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.FindByCriteriaResponse")
    @WebMethod
    public java.util.List<ar.com.templateit.cds.web.service.Producto> findByCriteria(
        @WebParam(name = "codigo", targetNamespace = "")
        java.lang.Long codigo,
        @WebParam(name = "nombre", targetNamespace = "")
        java.lang.String nombre,
        @WebParam(name = "descripcion", targetNamespace = "")
        java.lang.String descripcion,
        @WebParam(name = "categoria", targetNamespace = "")
        ar.com.templateit.cds.web.service.Categoria categoria
    );
}
