package ar.com.templateit.cds.web.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Jan 29 17:29:12 ARST 2016
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://service.web.cds.templateit.com.ar/", name = "UsuarioEcommerceService")
@XmlSeeAlso({ObjectFactory.class})
public interface UsuarioEcommerceService {

    @WebResult(name = "loadUsuarioEcommerce", targetNamespace = "")
    @RequestWrapper(localName = "loadUsuarioEcommerce", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.LoadUsuarioEcommerce")
    @ResponseWrapper(localName = "loadUsuarioEcommerceResponse", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.LoadUsuarioEcommerceResponse")
    @WebMethod
    public ar.com.templateit.cds.web.service.UsuarioEcommerce loadUsuarioEcommerce(
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @RequestWrapper(localName = "delete", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.DeleteResponse")
    @WebMethod
    public void delete(
        @WebParam(name = "usuario", targetNamespace = "")
        ar.com.templateit.cds.web.service.UsuarioEcommerce usuario
    );

    @WebResult(name = "getUsuarioEcommerceById", targetNamespace = "")
    @RequestWrapper(localName = "getUsuarioEcommerceById", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.GetUsuarioEcommerceById")
    @ResponseWrapper(localName = "getUsuarioEcommerceByIdResponse", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.GetUsuarioEcommerceByIdResponse")
    @WebMethod
    public ar.com.templateit.cds.web.service.UsuarioEcommerce getUsuarioEcommerceById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @RequestWrapper(localName = "update", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.UpdateResponse")
    @WebMethod
    public void update(
        @WebParam(name = "usuario", targetNamespace = "")
        ar.com.templateit.cds.web.service.UsuarioEcommerce usuario
    );

    @RequestWrapper(localName = "save", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.web.cds.templateit.com.ar/", className = "ar.com.templateit.cds.web.service.SaveResponse")
    @WebMethod
    public void save(
        @WebParam(name = "usuario", targetNamespace = "")
        ar.com.templateit.cds.web.service.UsuarioEcommerce usuario
    );
}
