
/*
 * 
 */

package ar.com.templateit.cds.web.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import ar.com.templateit.cds.web.service.CategoriaService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Sun Jan 24 22:39:35 ARST 2016
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "CategoriaServiceImplService", 
                  wsdlLocation = "http://localhost:8080/ventas/services/CategoriaService?WSDL",
                  targetNamespace = "http://impl.service.web.cds.templateit.com.ar/") 
public class CategoriaServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.service.web.cds.templateit.com.ar/", "CategoriaServiceImplService");
    public final static QName CategoriaServiceImplPort = new QName("http://impl.service.web.cds.templateit.com.ar/", "CategoriaServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ventas/services/CategoriaService?WSDL");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/ventas/services/CategoriaService?WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CategoriaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CategoriaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CategoriaServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns CategoriaService
     */
    @WebEndpoint(name = "CategoriaServiceImplPort")
    public CategoriaService getCategoriaServiceImplPort() {
        return super.getPort(CategoriaServiceImplPort, CategoriaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CategoriaService
     */
    @WebEndpoint(name = "CategoriaServiceImplPort")
    public CategoriaService getCategoriaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CategoriaServiceImplPort, CategoriaService.class, features);
    }

}
