
/*
 * 
 */

package ar.com.templateit.cds.web.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import ar.com.templateit.cds.web.service.ProductoService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Sun Jan 24 22:40:39 ARST 2016
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "ProductoServiceImplService", 
                  wsdlLocation = "http://localhost:8080/ventas/services/ProductoService?WSDL",
                  targetNamespace = "http://impl.service.web.cds.templateit.com.ar/") 
public class ProductoServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.service.web.cds.templateit.com.ar/", "ProductoServiceImplService");
    public final static QName ProductoServiceImplPort = new QName("http://impl.service.web.cds.templateit.com.ar/", "ProductoServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ventas/services/ProductoService?WSDL");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/ventas/services/ProductoService?WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ProductoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductoServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ProductoService
     */
    @WebEndpoint(name = "ProductoServiceImplPort")
    public ProductoService getProductoServiceImplPort() {
        return super.getPort(ProductoServiceImplPort, ProductoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductoService
     */
    @WebEndpoint(name = "ProductoServiceImplPort")
    public ProductoService getProductoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ProductoServiceImplPort, ProductoService.class, features);
    }

}
