
/*
 * 
 */

package ar.com.templateit.cds.web.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import ar.com.templateit.cds.web.service.UsuarioEcommerceService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Jan 29 17:29:12 ARST 2016
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "UsuarioEcommerceServiceImplService", 
                  wsdlLocation = "http://localhost:8080/ventas/services/UsuarioService?WSDL",
                  targetNamespace = "http://impl.service.web.cds.templateit.com.ar/") 
public class UsuarioEcommerceServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.service.web.cds.templateit.com.ar/", "UsuarioEcommerceServiceImplService");
    public final static QName UsuarioEcommerceServiceImplPort = new QName("http://impl.service.web.cds.templateit.com.ar/", "UsuarioEcommerceServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ventas/services/UsuarioService?WSDL");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/ventas/services/UsuarioService?WSDL");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UsuarioEcommerceServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UsuarioEcommerceServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioEcommerceServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns UsuarioEcommerceService
     */
    @WebEndpoint(name = "UsuarioEcommerceServiceImplPort")
    public UsuarioEcommerceService getUsuarioEcommerceServiceImplPort() {
        return super.getPort(UsuarioEcommerceServiceImplPort, UsuarioEcommerceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioEcommerceService
     */
    @WebEndpoint(name = "UsuarioEcommerceServiceImplPort")
    public UsuarioEcommerceService getUsuarioEcommerceServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UsuarioEcommerceServiceImplPort, UsuarioEcommerceService.class, features);
    }

}
